#!/bin/bash

u="apache"
g="apache"

echo "Changing ownership to ${u}:${g}"
chown -R ${u}:${g} ./

chmod 775 `find ./ -type d`

echo "Changing files to 0664"
chmod 664 `find ./ -type f | grep -v "${0}"`

echo "Fixing special files & dirs"
chmod 775 ./clearCaches
chmod 775 ./dbdApp/dbdcli
chmod 777 ./dbdApp/cache
chmod 777 ./dbdApp/assets/images/cache
chmod 777 ./dbdApp/views/.templates_c

echo "Done..."
